//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenInGeneralEducationInstitution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_TimeOfUse
    {
        public int ID_Class_TimeOfUse_RK { get; set; }
        public Nullable<int> ID_Class_FK { get; set; }
        public Nullable<int> ID_TimeOfUse_FK { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual TimeOfUse TimeOfUse { get; set; }
    }
}
