//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenInGeneralEducationInstitution
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinningRoom
    {
        public int ID_DinningRoom { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Supply_FK { get; set; }
        public Nullable<int> ID_Buffet_FK { get; set; }
        public Nullable<int> ID_TimeOfUse_FK { get; set; }
    
        public virtual Buffet Buffet { get; set; }
        public virtual Supply Supply { get; set; }
        public virtual TimeOfUse TimeOfUse { get; set; }
    }
}
