//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenInGeneralEducationInstitution
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administration> Administration { get; set; }
        public virtual DbSet<Buffet> Buffet { get; set; }
        public virtual DbSet<Buffet_Dish> Buffet_Dish { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Class_TimeOfUse> Class_TimeOfUse { get; set; }
        public virtual DbSet<Competence> Competence { get; set; }
        public virtual DbSet<DinningRoom> DinningRoom { get; set; }
        public virtual DbSet<Dish> Dish { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<ProfessionalArea> ProfessionalArea { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Sale_Dish> Sale_Dish { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentCategory> StudentCategory { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<Time> Time { get; set; }
        public virtual DbSet<TimeOfUse> TimeOfUse { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkShift> WorkShift { get; set; }
    }
}
