//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenInGeneralEducationInstitution
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOfUse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeOfUse()
        {
            this.Class_TimeOfUse = new HashSet<Class_TimeOfUse>();
            this.DinningRoom = new HashSet<DinningRoom>();
        }
    
        public int ID_TimeOfUse_RK { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> BeginingTime { get; set; }
        public Nullable<System.TimeSpan> EndingTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_TimeOfUse> Class_TimeOfUse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinningRoom> DinningRoom { get; set; }
    }
}
