//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenInGeneralEducationInstitution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public int ID_Time_RK { get; set; }
        public Nullable<System.TimeSpan> Name { get; set; }
    }
}
