//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenInGeneralEducationInstitution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID_Users_RK { get; set; }
        public Nullable<int> ID_Student_FK { get; set; }
        public string Code { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
